import { Note } from "@/lib/notes/types";
import { siteConfig } from "@/config/site";

// Fallback public notes used when Supabase is not configured.
// These mirror the markdown files in content/notes/*.md.

const substackLine = `for long-form writing, see [The Numismatica](${siteConfig.substackUrl}).`;

export const FALLBACK_PUBLIC_NOTES: Note[] = [
  {
    id: "about-me-fallback",
    slug: "about-me",
    title: "about me",
    content: [
      "👋 about me",
      "",
      substackLine,
      "",
      "# about me",
      "",
      "my name is ishita.",
      "",
      "i build at the intersection of crypto infrastructure and AI-native workflows.",
      "",
      "currently",
      "- operating across strategic execution, product systems, and capital in crypto infrastructure",
      "- scaled a treasury product to ~$300M AUM",
      "- supported a ~$70M Seed + Series A raise",
      "- built repeatable negotiation and launch execution playbooks",
      "- designing systems for research → decision → execution",
      "",
      "previously",
      "- investment & strategic execution at avail",
      "  • led investor relations and assisted ~$70M raise",
      "  • coordinated token launch execution with vendors, incentives, and comms",
      "- research & execution at elixir capital",
      "  • originated and led high-conviction infrastructure deal with strong outcome",
      "  • published widely-read research",
      "- research partner at woodstock fund",
      "  • ended deals end-to-end and built diligence frameworks for infra + token design",
      "- practice school (market risk) at deutsche bank",
      "  • worked on derivatives exposure and VaR modeling",
      "- academic foundations at bits pilani goa",
      "  • published peer-reviewed research in applied AI",
      "  • teaching assistant (thermodynamics)",
      "  • academic department secretary",
      "",
    ].join("\n"),
    emoji: "👋",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "about",
  },
  {
    id: "quick-links-fallback",
    slug: "quick-links",
    title: "quick links",
    content: [
      "📎 quick links",
      "",
      "# quick links",
      "",
      "- about me",
      "- work timeline",
      "- case studies",
      "- playbooks",
      "- talks & media",
      "- mentoring & community",
      "- contact",
      "",
    ].join("\n"),
    emoji: "📎",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "navigation",
  },
  {
    id: "principles-fallback",
    slug: "principles",
    title: "principles",
    content: [
      "📖 principles",
      "",
      "# principles",
      "",
      "this is the system i use to make decisions and ship work.",
      "",
      "1) find the real constraint",
      "   - not the hand-wavy blocker",
      "   - the thing that most limits progress",
      "",
      "2) make uncertainty explicit",
      "   - list assumptions",
      "   - list disconfirming evidence",
      "   - update as data arrives",
      "",
      "3) break ambiguity into decision trees",
      "   - clear paths, clear thresholds",
      "   - not opinions, but structured forks",
      "",
      "4) optimize for clarity, then for velocity",
      "   - clarity first reduces waste",
      "   - velocity next drives impact",
      "",
      "5) ship systems not one-offs",
      "   - reusable patterns > one-time wins",
      "",
      "6) hold leverage, not ego",
      "   - ask: “what is the smallest action that changes the outcome?”",
      "",
    ].join("\n"),
    emoji: "📖",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "principles",
  },
  {
    id: "bookmarks-fallback",
    slug: "bookmarks",
    title: "bookmarks",
    content: [
      "📚 bookmarks",
      "",
      "# bookmarks",
      "",
      "these are tools, frameworks, and foundational references i return to.",
      "",
      "- negotiation framework",
      "- launch execution checklist",
      "- investor relations playbook",
      "- token design incentive map",
      "- AI research-to-decision loop templates",
      "",
    ].join("\n"),
    emoji: "📚",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "references",
  },
  {
    id: "on-repeat-fallback",
    slug: "on-repeat",
    title: "on repeat",
    content: [
      "🔁 on repeat",
      "",
      "# on repeat",
      "",
      "songs that i listen to when i’m thinking deeply or grinding work cycles.",
      "",
      "- (add tracks you like)",
      "- (add tracks you like)",
      "- (add tracks you like)",
      "",
      "keep it personal. this note stays blank until you decide what belongs here.",
      "",
    ].join("\n"),
    emoji: "🔁",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "music",
  },
  {
    id: "reading-list-fallback",
    slug: "reading-list",
    title: "reading list",
    content: [
      "📘 reading list",
      "",
      "# reading list",
      "",
      "a regularly updated list of books and essays that sharpen my models.",
      "",
      "- systems thinking texts",
      "- negotiation and game theory primers",
      "- essays on crypto infrastructure design",
      "- AI decision frameworks and applied workflows",
      "",
      "leave blanks or add titles you’re currently reading.",
      "",
    ].join("\n"),
    emoji: "📘",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "reading",
  },
  {
    id: "favorite-blogs-fallback",
    slug: "favorite-blogs",
    title: "favorite blogs",
    content: [
      "📰 favorite blogs",
      "",
      "# favorite blogs",
      "",
      "blogs that influence how i think about systems, markets, and strategy.",
      "",
      "- (add blogs you check regularly)",
      "- (add newsletters you follow)",
      "- (add authors you read often)",
      "",
    ].join("\n"),
    emoji: "📰",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "reading",
  },
];


