import { Note } from "@/lib/notes/types";
import { siteConfig } from "@/config/site";

// Fallback public notes used when Supabase is not configured.
// These mirror the markdown files in content/notes/*.md.

const substackLine = `for long-form writing, see [The Numismatica](${siteConfig.substackUrl}).`;

export const FALLBACK_PUBLIC_NOTES: Note[] = [
  {
    id: "about-me-fallback",
    slug: "about-me",
    title: "about me",
    content: [
      substackLine,
      "",
      "my name is ishita.",
      "",
      "i build at the intersection of crypto infrastructure and AI-native workflows.",
      "",
      "currently",
      "- operating across strategic execution, product systems, and capital in crypto infrastructure",
      "- scaled a treasury product to ~$300M AUM",
      "- supported a ~$70M Seed + Series A raise",
      "- built repeatable negotiation and launch execution playbooks",
      "- designing systems for research → decision → execution",
      "",
      "previously",
      "- investment & strategic execution at avail",
      "  • led investor relations and assisted ~$70M raise",
      "  • coordinated token launch execution with vendors, incentives, and comms",
      "- research & execution at elixir capital",
      "  • originated and led high-conviction infrastructure deal with strong outcome",
      "  • published widely-read research",
      "- research partner at woodstock fund",
      "  • ended deals end-to-end and built diligence frameworks for infra + token design",
      "- practice school (market risk) at deutsche bank",
      "  • worked on derivatives exposure and VaR modeling",
      "- academic foundations at bits pilani goa",
      "  • published peer-reviewed research in applied AI",
      "  • teaching assistant (thermodynamics)",
      "  • academic department secretary",
      "",
    ].join("\n"),
    emoji: "👋",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "about",
  },
  {
    id: "quick-links-fallback",
    slug: "quick-links",
    title: "quick links",
    content: [
      "# quick links",
      "",
      "selected work and references that are a good starting point if you're trying to understand what i’ve been building and thinking about lately.",
      "",
      "- **Avail – $27M seed (Founders Fund)** · [Reuters](https://www.reuters.com/technology/peter-thiels-founders-fund-backs-27-mln-funding-avail-2024-02-26/)",
      "- **Avail – $43M Series A** · [The Block](https://www.theblock.co/post/298374/peter-thiel-founders-fund-series-a-avail)",
      "- **Hub71 crypto accelerator** · [Program overview](https://www.hub71.com/program/hub71-plus-digital-assets)",
      "- **Filecoin virtual machine report** · [X thread](https://x.com/FilecoinTLDR/status/1689270961218973696)",
      "- **MetaSky fundraise** · [Sequoia India & Woodstock announcement](https://timesofindia.indiatimes.com/web3-community-platform-metasky-brings-in-usd-1-8-million-led-by-sequoia-capital-india-woodstock-fund/articleshow/90398554.cms)",
      "",
      substackLine,
      "",
    ].join("\n"),
    emoji: "📎",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "navigation",
  },
  {
    id: "principles-fallback",
    slug: "principles",
    title: "principles",
    content: [
      "# principles",
      "",
      "this is the system i use to make decisions and ship work.",
      "",
      "1) find the real constraint",
      "   - not the hand-wavy blocker",
      "   - the thing that most limits progress",
      "",
      "2) make uncertainty explicit",
      "   - list assumptions",
      "   - list disconfirming evidence",
      "   - update as data arrives",
      "",
      "3) break ambiguity into decision trees",
      "   - clear paths, clear thresholds",
      "   - not opinions, but structured forks",
      "",
      "4) optimize for clarity, then for velocity",
      "   - clarity first reduces waste",
      "   - velocity next drives impact",
      "",
      "5) ship systems not one-offs",
      "   - reusable patterns > one-time wins",
      "",
      "6) hold leverage, not ego",
      "   - ask: “what is the smallest action that changes the outcome?”",
      "",
    ].join("\n"),
    emoji: "📖",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "principles",
  },
  {
    id: "bookmarks-fallback",
    slug: "bookmarks",
    title: "bookmarks",
    content: [
      "# bookmarks",
      "",
      "these are tools, frameworks, and foundational references i return to.",
      "",
      "- negotiation framework",
      "- launch execution checklist",
      "- investor relations playbook",
      "- token design incentive map",
      "- AI research-to-decision loop templates",
      "",
    ].join("\n"),
    emoji: "📚",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "references",
  },
  {
    id: "on-repeat-fallback",
    slug: "on-repeat",
    title: "on repeat",
    content: [
      "# on repeat",
      "",
      "songs that i listen to when i’m thinking deeply or grinding work cycles.",
      "",
      "- (add tracks you like)",
      "- (add tracks you like)",
      "- (add tracks you like)",
      "",
      "keep it personal. this note stays blank until you decide what belongs here.",
      "",
    ].join("\n"),
    emoji: "🔁",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "music",
  },
  {
    id: "reading-list-fallback",
    slug: "reading-list",
    title: "reading list",
    content: [
      "# reading list",
      "",
      "a running log of books that change how i think about building, leadership, and systems.",
      "",
      "## currently reading",
      "",
      "- ⏳ (add what i’m reading right now)",
      "",
      "## core reads",
      "",
      "- ✅ [The Hard Thing About Hard Things](https://www.goodreads.com/book/show/18176747-the-hard-thing-about-hard-things) — Ben Horowitz",
      "  - she’s the ceo. i’ve fan-mailed ben horowitz about this book and gifted copies to founders i work with.",
      "",
      "- ✅ [Range](https://www.goodreads.com/book/show/41795733-range) — David Epstein",
      "  - 15/10 well‑researched book on how generalists rule the world.",
      "",
      "- ✅ [Hooked](https://www.goodreads.com/book/show/22668729-hooked) — Nir Eyal",
      "  - this book got me out of a reading slump. it’s a very hooky book about why certain products pull people back again and again.",
      "",
      "- ✅ [Shoe Dog](https://www.goodreads.com/book/show/27220736-shoe-dog) — Phil Knight",
      "  - i read this while traveling in japan. also the reason i now have a mild irrational hatred for onitsuka tigers (shakes fist at kitami).",
      "",
      "- ✅ [The Long Way to a Small, Angry Planet](https://www.goodreads.com/book/show/22733729-the-long-way-to-a-small-angry-planet) — Becky Chambers",
      "  - cozy sci‑fi about life on a small spaceship drifting through the galaxy. not epic space battles—just people, relationships, and quiet moments in a very big universe.",
      "",
    ].join("\n"),
    emoji: "📘",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "reading",
  },
  {
    id: "favorite-blogs-fallback",
    slug: "favorite-blogs",
    title: "favorite blogs",
    content: [
      "# favorite blogs",
      "",
      "blogs that influence how i think about systems, markets, and strategy.",
      "",
      "- (add blogs you check regularly)",
      "- (add newsletters you follow)",
      "- (add authors you read often)",
      "",
    ].join("\n"),
    emoji: "📰",
    public: true,
    created_at: new Date().toISOString(),
    session_id: null,
    category: "reading",
  },
];


